name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Toolchain
        run: rustup install nightly-2024-02-03 && rustup default nightly-2024-02-03 && rustup target add wasm32-unknown-unknown
      - name: Dep
        run: cargo install cargo-leptos
      - name: Build
        run: RUSTFLAGS=--cfg=web_sys_unstable_apis cargo leptos build --release
