name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Toolchain cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy, rust-analyzer

      - name: Dep leptos
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-leptos
      - name: Toolchain leptos
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-02-03
          override: true
          target: wasm32-unknown-unknown
          components: rustfmt, clippy, rust-analyzer
      - name: Dep leptos
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: -f wasm-bindgen-cli --version 0.2.89
      - name: Build
        run: RUSTFLAGS=--cfg=web_sys_unstable_apis cargo leptos build --release
