name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy, rust-analyzer

      - name: Dep
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-leptos
      - name: Wasm
        run: rustup target add wasm32-unknown-unknown
      - name: Build
        run: RUSTFLAGS=--cfg=web_sys_unstable_apis cargo leptos build --release
