name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Dep
        run: cargo install trunk cargo-leptos
      - name: Build
        run: RUSTFLAGS=--cfg=web_sys_unstable_apis cargo leptos build --release
      - name: Run tests
        run: cargo leptos test
